version: "3"

services: 
    api:
        container_name: movie_api
        restart: always
        build:
          context: .
          dockerfile: backend.Dockerfile
        ports: 
            - "5000:3000"
        links: 
            - mongo
        environment: 
            - DB_HOST=mongo
            - DB_USER=api_user
            - DB_PASSWORD=api1234
            - DB_NAME=db_platzivideos
    mongo:
        container_name: db_mongo
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017
        volumes:
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    web: 
      container_name: platzivideos
      build:
        context: .
        dockerfile: ./frontend.Dockerfile
      ports:
        - 3000:3000

    testing:
      container_name: test_cypress
      build:
        context: .
        # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
        dockerfile: ./cypress.Dockerfile
      image: cypress
      depends_on:
        - web
      environment:
        # pass base url to test pointing at the web application
        - CYPRESS_baseUrl=http://web:3000
        - DISPLAY
      # share the current folder as volume to avoid copying
      working_dir: /e2e
      volumes:
        - ./e2e:/e2e
        - /tmp/.X11-unix:/tmp/.X11-unix
      entrypoint: cypress open --project /e2e
    