version: "3"

services: 
    api:
        container_name: movie_api
        restart: always
        build:
          context: .
          dockerfile: backend.Dockerfile
        ports: 
            - "5000:3000"
        links: 
            - mongo
        environment: 
            - DB_HOST=mongo
            - DB_USER=api_user
            - DB_PASSWORD=api1234
            - DB_NAME=db_platzivideos
    mongo:
        container_name: db_mongo
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017
        volumes:
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    web: 
      container_name: platzivideos
      build:
        context: .
        dockerfile: ./frontend.Dockerfile
      ports:
        - 3000:3000

    # db-client:
    #     container_name: db-client
    #     image: "mongoclient/mongoclient:4.0.0"
    #     # restart: always
    #     ports: 
    #         - "3000:3000"
    #     depends_on:
    #       - web
    #     environment: 
    #         - ROOT_URL= http://mongo:27017/admin